version: '2'
services:
    php-fpm:
        build: docker/php-fpm
        links:
            - mysql:mysql
        volumes:
            - ./:/app

    php-cli:
        build:
            context: docker/php-cli
        working_dir: /app
        volumes:
             - ./:/app
        links:
             - mysql:mysql
        tty: true

    nginx:
        image: nginx:stable-alpine
        links:
            - php-fpm:fpm
        volumes:
                - ./docker/nginx/vhost.conf:/tmp/vhost.conf
                - ./:/app
                - ./docker/logs:/log
        command: /bin/sh -c "envsubst '$$DOMAIN ' < /tmp/vhost.conf > /etc/nginx/conf.d/vhost.conf  && nginx -g 'daemon off;'"

    mysql:
        build: docker/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=toor
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - 127.0.0.1:3306:3306
        command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mysql:db
volumes:
    mysql-data:
        driver: local
